# Generated by Django 3.0.6 on 2021-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20210401_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
